spring:
  application:
    name: game
  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: postgres
    password: det
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  messages:
    basename: messages
    encoding: UTF-8
  web:
    locale: vi
    locale-resolver: accept-header

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: game-files

swagger:
  host-url: http://0.0.0.0:8080

server:
  port: 8080
