spring:
  application:
    name: game
  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: postgres
    password: det
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  basename: messages
  encodeding: UTF-8

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: game-files

swagger:
  host-url: http://0.0.0.0:8080

server:
  port: 8080
